from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from pollicino.net.link import FragmentFrame


TRANSFER_ID = 0x504E4631
INNER_PAYLOAD = bytes(
    [
        0x00,
        0xFF,
        0x01,
        0xFE,
        0x7F,
        0x80,
        0x10,
        0x20,
        0x30,
        0x40,
        0x50,
        0x60,
        0x70,
        0x90,
        0xA0,
        0xB0,
        0xC0,
        0xD0,
        0xE0,
        0xF0,
    ]
) + b"PollicinoNet-PNF1-over-LoRaMesher"


def build_fixture() -> bytes:
    """Return one real PNF1 frame produced by production encoder code."""

    return FragmentFrame(
        transfer_id=TRANSFER_ID,
        sequence=0,
        total=1,
        payload=INNER_PAYLOAD,
    ).encode()


def render_header(frame: bytes) -> str:
    digest = hashlib.sha256(frame).hexdigest()
    values = ", ".join(f"0x{value:02X}" for value in frame)
    return f"""#pragma once

#include <cstdint>
#include <vector>

// Generated by scripts/emit_loramesher_pnf1_fixture.py using
// pollicino.net.link.FragmentFrame.encode(). Do not hand-edit.
// SHA-256: {digest}
inline const std::vector<uint8_t> kPollicinoPnf1Payload = {{{values}}};
inline constexpr std::size_t kPollicinoPnf1PayloadSize = {len(frame)};
inline constexpr const char* kPollicinoPnf1Sha256 = "{digest}";
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    frame = build_fixture()
    # The fixture itself must round-trip before it is handed to an external
    # bearer. This keeps a future LoRaMesher failure distinct from bad PNF1.
    decoded = FragmentFrame.decode(frame)
    if decoded.payload != INNER_PAYLOAD or decoded.transfer_id != TRANSFER_ID:
        raise AssertionError("generated PNF1 fixture failed local round-trip")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_header(frame), encoding="utf-8", newline="\n")
    print(f"PNF1_BYTES={len(frame)}")
    print(f"PNF1_SHA256={hashlib.sha256(frame).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
