[platformio]
default_envs = lilygo_v161_minisketch_probe

[env:lilygo_v161_minisketch_probe]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DDISABLE_DEFAULT_FIELDS
    -DENABLE_FIELD_16
    -Ilib/minisketch/include
    -Ilib/minisketch/src
