[platformio]
default_envs = lilygo_lora32_v161_sx1276

[env:lilygo_lora32_v161_sx1276]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib@7.6.0
build_flags =
    -DHW001_LILYGO_LORA32_V161
build_src_filter =
    +<*>
    -<hw003.cpp>
    -<hw005.cpp>
    -<hw006.cpp>

[env:lilygo_lora32_v161_sx1276_hw003]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib@7.6.0
build_flags =
    -DHW001_LILYGO_LORA32_V161
build_src_filter =
    -<*>
    +<hw003.cpp>

[env:lilygo_lora32_v161_sx1276_hw005]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib@7.6.0
build_flags =
    -DHW001_LILYGO_LORA32_V161
build_src_filter =
    -<*>
    +<hw005.cpp>

[env:lilygo_lora32_v161_sx1276_hw006]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib@7.6.0
build_flags =
    -DHW001_LILYGO_LORA32_V161
build_src_filter =
    -<*>
    +<hw006.cpp>
